services:
  app-manager:
    build: ./app-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/host
      - /tmp/repos:/tmp/repos
      - ./app-manager/apps:/app/apps
      - ./nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app
    environment:
      - NODE_ENV=production
      - HOST_PROJECT_ROOT=/host
      - NGINX_CONTAINER_NAME=devops-nginx-1
      - COMPOSE_PROJECT_NAME=devops
    expose:
      - '3002'
    networks:
      - projects-network
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dashboard.html:/usr/share/nginx/html/dashboard.html
    depends_on:
      - app-manager
    networks:
      - projects-network
    restart: unless-stopped
networks:
  projects-network:
    driver: bridge
